---
title: "Data Integration"
author: "Megan Schumer"
date: '`r Sys.Date()`'
output: pdf_document
toc: TRUE
---

## start-up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## setup

```{r packages, include=FALSE}

# load libraries
library(tidyverse)
library(readxl)

# APA formatting
theme_apa <- papaja::theme_apa

# variable for current date
datetoday <- Sys.Date()

# variable for data folder
existing_folder <- "data"

# create folder inside data folder named with current date
new_folder <- file.path(existing_folder, datetoday)
dir.create(new_folder)
```

## import datasets and aux files

```{r datasets}

# upload dataset files and clean up headers
redcap_data <- read_csv("data/raw/redcap_data.csv") %>%
  janitor::clean_names()

timestamps <- read_csv("data/raw/merged_events_data.csv") %>%
  janitor::clean_names()

blink_data <- read_csv("data/raw/merged_blinks_data_2024-05-02.csv") %>%
  janitor::clean_names()
```

```{r auxiliaries}

# load HBQ aux file for categorizing questions for subscales

hbq_items <- read_csv("auxiliaries/hbq_items.csv")
```

## clean up data

```{r demo}

# replace NA values in race columns with 0

redcap_data$demo_child_race_6 <- replace_na(redcap_data$demo_child_race_6, 0)
redcap_data$demo_race_6 <- replace_na(redcap_data$demo_race_6, 0)

# filter out enrollment/recruitment arms

redcap_data <- filter(redcap_data, redcap_event_name == "t1_arm_1" | redcap_event_name == "t1_arm_2" | redcap_event_name == "pcat_arm_1" | redcap_event_name == "pcat_arm_4") %>%
  
  # calculate parent and child ages in months and years
  
  mutate(c_age_y = time_length(interval(demo_child_dob,tsst_date),"year"),
         c_age_m = time_length(interval(demo_child_dob,tsst_date),"month"),
         p_age_y = time_length(interval(demo_dob,tsst_date),"year"),
         p_age_m = time_length(interval(demo_dob,tsst_date),"month")) %>%
  
  # combine race columns into one and convert to factor
  
  mutate(c_race = factor(case_when(
    demo_child_race_6 == 1 | demo_child_race_1 + demo_child_race_2 + demo_child_race_3 + demo_child_race_4 + demo_child_race_5 + demo_child_race_7 > 1 ~ 6,
    demo_child_race_1 == 1 ~ 1,
    demo_child_race_2 == 1 ~ 2,
    demo_child_race_3 == 1 ~ 3,
    demo_child_race_4 == 1 ~ 4,
    demo_child_race_5 == 1 ~ 5,
    demo_child_race_7 == 1 ~ 7,
    .default = NA
  ),
  levels = c(1:7, NA),
  labels = c("White", "Black/African American", "Asian", "Native Hawaiian/Pacific Islander", "American Indian/Alaskan Native", "Multiracial", "Other")),
  p_race = factor(case_when(
    demo_race_6 == 1 | demo_race_1 + demo_race_2 + demo_race_3 + demo_race_4 + demo_race_5 + demo_race_7 > 1 ~ 6,
    demo_race_1 == 1 ~ 1,
    demo_race_2 == 1 ~ 2,
    demo_race_3 == 1 ~ 3,
    demo_race_4 == 1 ~ 4,
    demo_race_5 == 1 ~ 5,
    demo_race_7 == 1 ~ 7,
    .default = NA
  ),
  levels = c(1:7, NA),
  labels = c("White", "Black/African American", "Asian", "Native Hawaiian/Pacific Islander", "American Indian/Alaskan Native", "Multiracial", "Other"))) %>%
  
  # convert sex and ethnicity to factors and education and income to orders
  
  mutate(demo_child_sex = factor(demo_child_sex, levels = c(1:3, -999, NA), labels = c("Male", "Female", "Intersex", "Refused")),
         demo_sex = factor(demo_sex, levels = c(1:3,-999,NA), labels = c("Male", "Female", "Intersex", "Refused")),
         demo_child_ethnicity = factor(demo_child_ethnicity, levels = c(0:1, -999, NA), labels = c("Non-Hispanic/Latino", "Hispanic/Latino", "Refused")),
         demo_ethnicity = factor(demo_ethnicity, levels = c(0:1, -999, NA), labels = c("Non-Hispanic/Latino", "Hispanic/Latino", "Refused")),
         demo_degree = ordered(demo_degree, levels = c(1:9, -999, NA), labels = c("No Diploma or Degree", "GED", "High School Diploma", "Associate's Degree", "Bachelor's Degree", "Master's Degree", "Doctorate (PhD, MD, JD, etc.)", "Some College", "Other", "Refused")),
         demo_combinedincome = ordered(demo_combinedincome, levels = c(1:8, -999, NA), labels = c("Less than $20,000", "$20,000 to $39,999", "$40,000 to $59,999", "$60,000 to $79,999", "$80,000 to $99,999", "$100,000 to $119,999", "$120,000 to $250,000", "More than $250,000", "Refused")))
```

```{r hbq}

# select hbq data from main df

hbq_scores <- select(redcap_data, demo_recordid, hbq_68:hbq_136)
```

## narrow down variables

```{r child data}

# select and rename variables for child data

demo_child_data <- demo_data %>%
  select(record_id, c_age_m, c_age_y, c_sex, c_race, c_latinx, p_edu, income_house, ladder_country, ladder_community) %>%
  rename(age_m = c_age_m, age_y = c_age_y, sex = c_sex, race = c_race, latinx = c_latinx, parent_edu = p_edu, ses_country = ladder_country, ses_community = ladder_community) %>%
  mutate(parent_child = 1, .before = age_m) %>%
  mutate(record_id_chr = paste0(as.character(record_id), "_C"), .before = parent_child)
```

```{r demo_parent}

# select and rename variables for parent demo data

demo_parent_data <- demo_data %>%
  select(record_id, p_age_m, p_age_y, p_sex, p_race, p_latinx, p_edu, income_house, ladder_country, ladder_community) %>%
  rename(age_m = p_age_m, age_y = p_age_y, sex = p_sex, race = p_race, latinx = p_latinx, parent_edu = p_edu, ses_country = ladder_country, ses_community = ladder_community) %>%
  mutate(parent_child = 0, .before = age_m) %>%
  mutate(record_id_chr = paste0(as.character(record_id),"_P"), .before = parent_child)
```

```{r ep_child}

# select and rename variables for child ep questionnaire data

ep_child_data <- ep_data %>%
  select(record_id, preeptrier_1, preeptrier_2, preeptrier_3, preeptrier_4, posttrierc1, posttrierc2, posttrierc3, posttrier4) %>%
  rename(pre_anxiety = preeptrier_1, pre_joy = preeptrier_2, pre_success = preeptrier_3, pre_meta = preeptrier_4, post_anxiety = posttrierc1, post_joy = posttrierc2, post_success = posttrierc3, post_meta = posttrier4) %>%
  mutate(record_id_chr = paste0(as.character(record_id), "_C"), .before = pre_anxiety)
```

```{r ep_parent}

# select and rename variables for parent ep questionnaire data

ep_parent_data <- ep_data %>%
  select(record_id, preeptrier_1, preeptrier_2, preeptrier_3, preeptrier_4, posttrier1, posttrier2, posttrier3, posttrier4) %>%
  rename(pre_anxiety = preeptrier_1, pre_joy = preeptrier_2, pre_success = preeptrier_3, pre_meta = preeptrier_4, post_anxiety = posttrier1, post_joy = posttrier2, post_success = posttrier3, post_meta = posttrier4) %>%
  mutate(record_id_chr = paste0(as.character(record_id), "_P"), .before = pre_anxiety)
```

```{r hbq_child}

# select and rename variables for child hbq data
# calculate overall anxiety score

hbq_child_data <- hbq_data %>%
  select(record_id, hbq_internalizing_symptoms_overanxious, hbq_internalizing_symptoms_separation_anxiety, hbq_social_withdrawal_social_inhibition) %>%
  rename(overanxious = hbq_internalizing_symptoms_overanxious, separation_anxiety = hbq_internalizing_symptoms_separation_anxiety, social_inhibition = hbq_social_withdrawal_social_inhibition) %>%
  mutate(hbq_anxiety = overanxious + separation_anxiety + social_inhibition) %>%
  mutate(record_id_chr = paste0(as.character(record_id), "_C"), .before = overanxious) %>%
  filter(!is.na(overanxious) | !is.na(separation_anxiety) | !is.na(social_inhibition))
```

```{r hbq_parent}

# select and rename variables for parent hbq data
# calculate overall anxiety score

hbq_parent_data <- hbq_data %>%
  select(record_id, hbq_internalizing_symptoms_overanxious, hbq_internalizing_symptoms_separation_anxiety, hbq_social_withdrawal_social_inhibition) %>%
  rename(overanxious = hbq_internalizing_symptoms_overanxious, separation_anxiety = hbq_internalizing_symptoms_separation_anxiety, social_inhibition = hbq_social_withdrawal_social_inhibition) %>%
  mutate(hbq_anxiety = overanxious + separation_anxiety + social_inhibition) %>%
  mutate(record_id_chr = paste0(as.character(record_id), "_P"), .before = overanxious) %>%
  filter(!is.na(overanxious) | !is.na(separation_anxiety) | !is.na(social_inhibition))
```

```{r blinks}

# select and rename variables for blink data

blink_data <- mutate(blink_data, record_id_chr = paste0(as.character(id), "_", toupper(as.character(participant))))
```

```{r timestamps}

# create tables for cloud and recording timestamps
# pivot to create columns for each type of timestamp

timestamps_cloud <- pivot_wider(timestamps, names_from = name, values_from = timestamp_ns) %>%
  filter(type == "cloud")

timestamps_rec <- pivot_wider(timestamps, names_from = name, values_from = timestamp_ns) %>%
  filter(type == "recording")

# combine cloud and recording timestamps, clean up variable names

timestamp_data <- full_join(timestamps_cloud, timestamps_rec, join_by(recording_id)) %>%
  select(id.x, participant.x, recording.begin.y, pprep.start.x, pprep.end.x, pspeech.start.x, pspeech.end.x, cprep.start.x, cprep.end.x, cspeech.start.x, cspeech.end.x, recording.end.y) %>%
  rename(record_id = id.x, parent_child = participant.x, recording_begin = recording.begin.y, pprep_start = pprep.start.x, pprep_end = pprep.end.x, pspeech_start = pspeech.start.x, pspeech_end = pspeech.end.x, cprep_start = cprep.start.x, cprep_end = cprep.end.x, cspeech_start = cspeech.start.x, cspeech_end = cspeech.end.x, recording_end = recording.end.y) %>%
  mutate(record_id_chr = paste0(as.character(record_id), "_", toupper(as.character(parent_child))), .before = recording_begin)
```

## calculate durations and blink rates

```{r durations}

# calculate prep and speech durations in nanoseconds, convert to minutes

tsst_durations <- mutate(timestamp_data, pprep_duration_ns = pprep_end - pprep_start,
                         pprep_duration = (pprep_duration_ns * 10^-9)/60,
                         pspeech_duration_ns = pspeech_end - pspeech_start,
                         pspeech_duration = (pspeech_duration_ns * 10^-9)/60,
                         cprep_duration_ns = cprep_end - cprep_start,
                         cprep_duration = (cprep_duration_ns * 10^-9)/60,
                         cspeech_duration_ns = cspeech_end - cspeech_start,
                         cspeech_duration = (cspeech_duration_ns * 10^-9)/60,) %>%
  select(record_id_chr, pprep_duration, pspeech_duration, cprep_duration, cspeech_duration)
```

```{r blink counts}

# combine blink_data and timestamp_data so blinks can be categorized into different task sections

blink_counts <- inner_join(blink_data, timestamp_data, join_by(record_id_chr)) %>%
  
  # create column for blink categorization
  
  mutate(blink_type = case_when(
    start_timestamp_ns >= pprep_start & end_timestamp_ns <= pprep_end ~ "pprep_blinks",
    start_timestamp_ns >= pspeech_start & end_timestamp_ns <= pspeech_end ~ "pspeech_blinks",
    start_timestamp_ns >= cprep_start & end_timestamp_ns <= cprep_end ~ "cprep_blinks",
    start_timestamp_ns >= cspeech_start & end_timestamp_ns <= cspeech_end ~ "cspeech_blinks",
    .default = NA
  )) %>%
  
  # filter out blinks outside of task sections
  
  filter(!is.na(blink_type)) %>%
  
  # group by pt and blink type
  
  group_by(record_id_chr, blink_type) %>%
  
  # count number of blinks per task section per pt
  
  summarise(n = n()) %>%
  
  # pivot wider, one row per pt
  
  pivot_wider(names_from = blink_type, values_from = n)
```

```{r blink rates}

# combine blink_counts and tsst_durations so blink rate can be calculated

blink_rates <- full_join(blink_counts, tsst_durations) %>%
  
  # calculate blink rates
  
  mutate(pprep_blinkrate = pprep_blinks/pprep_duration,
         pspeech_blinkrate = pspeech_blinks/pspeech_duration,
         cprep_blinkrate = cprep_blinks/cprep_duration,
         cspeech_blinkrate = cspeech_blinks/cspeech_duration)
```

## combine tables

```{r parent_child}

# stack demo_child_data and demo_parent_data

demo_clean <- bind_rows(demo_child_data, demo_parent_data)

# stack ep_child_data and ep_parent_data

ep_clean <- bind_rows(ep_child_data, ep_parent_data)

# stack hbq_child_data and hbq_parent_data

hbq_clean <- bind_rows(hbq_child_data, hbq_parent_data)
```

```{r demo_ep_hbq}

# inner join demo_clean and ep_clean

data_complete <- inner_join(demo_clean, ep_clean, join_by(record_id_chr, record_id)) %>%
  
  # add hbq data
  
  inner_join(hbq_clean, join_by(record_id_chr, record_id)) %>%
  
  # add blink rates
  
  inner_join(blink_rates, join_by(record_id_chr))

# write data_complete to .csv

write.csv(data_complete, file = paste0(new_folder, "/data_complete.csv"), row.names = FALSE)
```

```{r abstract demographics}

# group into parents and children

data_complete_demo <- group_by(data_complete, parent_child) %>%
  
  # calculate summary stats for age in years
  
  summarise(mean = mean(age_y), min = min(age_y), max = max(age_y), sd = sd(age_y))
```