---
title: "Data Integration"
author: "Megan Schumer"
date: '`r Sys.Date()`'
output: pdf_document
toc: TRUE
---

## start-up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## setup

```{r packages, include=FALSE}

# load libraries
library(tidyverse)
library(readxl)

# variable for tidy data file path
existing_folder <- "../data/tidy"

# identify date/folder name of most recent tidy data output

# list files
tidy_folders <- list.dirs("../data/tidy", full.names = FALSE)
# identify most recent date
current_data <- tail(tidy_folders, 1)

# pull dataset from most recent data output
data_path <- file.path(existing_folder, current_data)
data_complete <- read_csv(paste0(data_path, "/data_complete.csv"))
```

## summary stats

```{r group data}

# calculate mean/SD for numeric data
summary_data_means <- pivot_longer(data_complete, cols = c(4:5, 11:28, 30:45), names_to = "variable_name") %>%
  
  # select relevant columns
  select(3, 10:11) %>%
  
  # remove any -99/-999 stragglers
  mutate(value = na_if(value, -999)) %>%
  mutate(value = na_if(value, -99)) %>%
  
  # group by parent/child and variable_name
  group_by(parent_child, variable_name) %>%
  
  # calculate mean/SD for each variable
  summarize(mean = mean(value, na.rm = TRUE), stdev = sd(value, na.rm = TRUE), count = sum(!is.na(value)), missing_values = sum(is.na(value)))

# calculate counts for sex, race, ethnicity, income, and education
summary_data_counts <- pivot_longer(data_complete, cols = c(6:10), names_to = "variable_name") %>%
  
  # select relevant columns
  select(3, 41:42) %>%
  
  # group by parent/child, variable_name, and value
  group_by(parent_child, variable_name, value) %>%
  
  # count by each demographic category
  summarize(count = n())

# count dyads
summary_data_dyads <- mutate(data_complete,
                             
                             # add columns to track completion of study tasks
                             demo_complete = case_when(
                               !if_all(4:12, is.na) ~ 1,
                               .default = 0
                             ),
                             hbq_complete = case_when(
                               !if_all(21:24, is.na) ~ 1,
                               .default = 0
                             ),
                             ep_complete = case_when(
                               !if_all(13:20, is.na) ~ 1,
                               .default = 0
                             ),
                             tsst_complete = case_when(
                               !if_all(c(25:28, 30:45), is.na) ~ 1,
                               .default = 0
                             ),
                             demo_complete_strict = case_when(
                               !if_any(4:12, is.na) ~ 1,
                               .default = 0
                             ),
                             hbq_complete_strict = case_when(
                               !if_any(21:24, is.na) ~ 1,
                               .default = 0
                             ),
                             ep_complete_strict = case_when(
                               !if_any(13:20, is.na) ~ 1,
                               .default = 0
                             ),
                             tsst_complete_strict = case_when(
                               !if_any(c(25:28, 30:45), is.na) ~ 1,
                               .default = 0
                             )) %>%
  
  # select relevant columns
  select(1, 3, 46:53) %>%
  
  # pivot completion data columns longer
  pivot_longer(cols = c(3:10), names_to = "completion_data") %>%
  
  # group by task completion and id
  group_by(completion_data, record_id) %>%
  
  # idk how to describe what i'm doing here, number of pts per dyad per completed task? if both parent and child completed it's 2, if only 1 did it's 1, if neither did it's 0
  summarize(dyad_completion = sum(value)) %>%
  
  # ungroup and then regroup by task completion and completion count (e.g., how many completed per dyad)
  ungroup() %>%
  group_by(completion_data, dyad_completion) %>%
  
  # count complete dyads, partial dyads, and no data for each task
  summarize(count = n())
```