---
title: "Graphs"
date: "`r Sys.Date()`"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load packages

install.packages('scales')
library(tidyverse)
library(ggplot2)
library(scales)
```

```{r}
#load data
data <- read.csv("C:/Users/talia/Box/tsst_anxiety_blinking/data/tidy/2024-09-10/data_complete.csv")

view(data)

blink_rates_s <- data %>%
  select(pprep_blinkrate_s, pspeech_blinkrate_s, cprep_blinkrate_s, cspeech_blinkrate_s, participant)

blink_rates_s <- blink_rates_s %>%
  rename(
    parent_prep = pprep_blinkrate_s,
    parent_speech = pspeech_blinkrate_s,
    child_prep = cprep_blinkrate_s,
    child_speech = cspeech_blinkrate_s
  )

blink_rates_s_long <- blink_rates_s %>%
  pivot_longer(cols = parent_prep:child_speech, names_to = "Condition", values_to = "Blinkrate")

head(blink_rates_s_long)

blink_rates_s_long <- blink_rates_s_long %>%
  mutate(participant = recode(participant, 
                              "c" = "Child",
                              "p" = "Parent"))

#assign colors for participants for bar graph
participant_colors <- c("Child" = "#EF5B5B", "Parent" = "#20A39E")

```

```{r}
##scatterplot##
str(blink_rates_s_long)

blink_rates_s_long |>
  ggplot(mapping = aes(x = Condition, y = Blinkrate, color = participant)) +
  geom_jitter(width = 0.2, height = 0) +
  scale_color_manual(values = participant_colors) +
  labs(title = "Blink Rates Across Conditions",
        x = "Task Condition",
        y = "Blinks per Second") 

```
```{r}
##Bargraph##

#calculate  summary stats
blink_rates_summary <- blink_rates_s_long %>%
  group_by(Condition, participant) %>%
  summarise(
    mean = mean(Blinkrate, na.rm = TRUE),
    se = sd(Blinkrate, na.rm = TRUE) / sqrt(n()),
    .groups = 'drop'
  )

#plot data

##base code for the bargraph
blink_rates_summary |>
  ggplot(aes(x = factor(Condition, levels = c("parent_prep", "parent_speech", "child_prep", "child_speech")), y = mean, fill = participant)) +
  geom_bar(stat = 'identity', position = position_dodge(), width = 0.7) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean +se), width = 0.2, position = position_dodge(0.7), size = 0.75) +
  scale_y_continuous(limits = c(0, 0.7), expand = c(0, 0)) +
  scale_color_manual(values = participant_colors) +
  labs(x = "Task Condition",
       y = "Blinks per Second",
       fill = "Participant") +
  scale_x_discrete(labels = function(x) str_wrap(c("parent_prep" = "Parent Prep",
                                                    "parent_speech" = "Parent Speech",
                                                    "child_prep" = "Child Prep",
                                                    "child_speech" = "Child Speech"), width = 10)) +
  theme(
    panel.background = element_blank(),
    panel.grid = element_blank(),
    axis.line = element_line(color = "black", size = 0.75),
    axis.text = element_text(color = 'black', size = 28),
    axis.title = element_text(size = 32),
    legend.title = element_text(size = 28),
    legend.text = element_text(size = 26)
  )


##making data bargraph item so i can save picture
bargraph <- blink_rates_summary |>
  ggplot(aes(x = factor(Condition, levels = c("parent_prep", "parent_speech", "child_prep", "child_speech")), y = mean, fill = participant)) +
  geom_bar(stat = 'identity', position = position_dodge(), width = 0.7) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean +se), width = 0.2, position = position_dodge(0.7), size = 0.75) +
  scale_y_continuous(limits = c(0, 0.7), expand = c(0, 0)) +
  scale_color_manual(values = participant_colors) +
  labs(x = "Task Condition",
       y = "Blinks per Second",
       fill = "Participant") +
  scale_x_discrete(labels = c("parent_prep" = "Parent Prep",
                              "parent_speech" = "Parent Speech",
                              "child_prep" = "Child Prep",
                              "child_speech" = "Child Speech")) +
  theme(
    panel.background = element_blank(),
    panel.grid = element_blank(),
    axis.line = element_line(color = "black", size = 0.75),
    axis.text = element_text(color = 'black', size = 44), 
    axis.title = element_text(size = 52),
    legend.title = element_text(size = 44),
    legend.text = element_text(size = 40)
  )

##save the picture
ggsave("blink_rates_plot.jpg", plot = bargraph, width = 24, height = 16, units = "in", dpi = 150)
```


```{r}
#Blinks vs HBQ (child)#

#prepare data set
child_data <- data %>%
  select(pre_meta, post_meta, hbq_anxiety, pprep_blinkrate_s, pspeech_blinkrate_s, cprep_blinkrate_s, cspeech_blinkrate_s, participant, age_y)

child_data <- child_data %>%
  rename(parent_prep = pprep_blinkrate_s,
    parent_speech = pspeech_blinkrate_s,
    child_prep = cprep_blinkrate_s,
    child_speech = cspeech_blinkrate_s,
    pre_ep = pre_meta,
    post_ep = post_meta,
    Age = age_y)

child_data <- child_data %>%
  filter(participant == 'c')

child_data <- child_data %>%
  select(-participant)

child_data_long <- child_data %>%
  pivot_longer(cols = pre_ep:post_ep, names_to = 'Questionnaire', values_to = 'Score')


#plot HBQ and pre/post EP based on age of child#

#jitterplot with pre_ep and anxiety; child age color

##base jitterplot
child_data |>
  ggplot(mapping = aes(x = pre_ep, y = hbq_anxiety, color = Age)) +
  geom_jitter(size = 2.5) +
  scale_y_continuous(limits = c(0, 6), expand = c(0.02, 0)) +
  scale_color_gradientn(colors = c("#20A39E", "#EF5B5B", "#FFBA49")) +
  labs(y = "HBQ Anxiety",
       x = "Pre-Task Questionnaire",
       fill = "Child Age") +
  theme(
    panel.background = element_blank(),
    panel.grid = element_blank(),
    axis.line = element_line(color = "black", size = 0.75),
    axis.text = element_text(color = 'black', size = 44), 
    axis.title = element_text(size = 52),
    legend.title = element_text(size = 44),
    legend.text = element_text(size = 40),
    legend.position = "none"
  )

##assigning plot to pre_ep to save
pre_ep <- child_data |>
  ggplot(mapping = aes(x = pre_ep, y = hbq_anxiety, color = Age)) +
  geom_jitter(size = 15) +
  scale_y_continuous(limits = c(0, 6), expand = c(0.02, 0)) +
  scale_color_gradientn(colors = c("#20A39E", "#EF5B5B", "#FFBA49")) +
  labs(y = "HBQ Anxiety",
       x = "Pre-Task Questionnaire",
       fill = "Child Age") +
  theme(
    panel.background = element_blank(),
    panel.grid = element_blank(),
    axis.line = element_line(color = "black", size = 0.75),
    axis.text = element_text(color = 'black', size = 44), 
    axis.title = element_text(size = 52),
    legend.position = "none"
  )

##save plot
ggsave("pre_ep_hbq.jpg", plot = pre_ep, width = 24, height = 16, units = "in", dpi = 150)


#jitterplot with post-ep and anxiety; child age color

##base code
child_data |>
  ggplot(mapping = aes(x = post_ep, y = hbq_anxiety, color = Age)) +
  geom_jitter(width = 0.25, size = 15) +
  scale_y_continuous(limits = c(0, 6), expand = c(0.02, 0)) +
  scale_color_gradientn(colors = c("#20A39E", "#EF5B5B", "#FFBA49")) +
  labs(y = "HBQ Anxiety",
       x = "Post-Task Questionnaire",
       fill = "Child Age") +
  theme(
    panel.background = element_blank(),
    panel.grid = element_blank(),
    axis.line = element_line(color = "black", size = 0.75),
    axis.text = element_text(color = 'black', size = 44), 
    axis.title = element_text(size = 52),
    legend.title = element_text(size = 44),
    legend.text = element_text(size = 40)
  )

##assign plot to post_ep
post_ep <- child_data |>
  ggplot(mapping = aes(x = post_ep, y = hbq_anxiety, color = Age)) +
  geom_jitter(width = 0.25, size = 15) +
  scale_y_continuous(limits = c(0, 6), expand = c(0.02, 0)) +
  scale_color_gradientn(colors = c("#20A39E", "#EF5B5B", "#FFBA49")) +
  labs(y = "HBQ Anxiety",
       x = "Post-Task Questionnaire",
       fill = "Child Age") +
  theme(
    panel.background = element_blank(),
    panel.grid = element_blank(),
    axis.line = element_line(color = "black", size = 0.75),
    axis.text = element_text(color = 'black', size = 44), 
    axis.title = element_text(size = 52),
    legend.title = element_text(size = 44),
    legend.text = element_text(size = 40)
  )  +
  guides(color = guide_colorbar(
    barwidth = 2,   # Increase the width of the color bar
    barheight = 20  # Increase the height of the color bar
  ))

##save graph
ggsave("post_ep_hbq.jpg", plot = post_ep, width = 24, height = 16, units = "in", dpi = 150)

```

